---

- hosts: all
  become: true
  tasks: 

  - name: update index
    apt:
      update_cache: true
      state: latest
  
  - name: install apache2
    apt: 
      name: apache2 

  - name: install php ressources
    apt:
      name: libapache2-mod-php
      state: latest
